---
- hosts: grp1
  become: true
  tasks:
    - name: create a group
      group:
        name: testgroup
        state: present

    - name: create a user
      user:
        name: testuser
        state: present
        group: testgroup
